### ISSUE TITLE
css居中 

### ISSUE THREAD

**Issue by hapiman** [hapiman/jsrice#18]
### 水平居中

- 行内元素
`text-align:center`

- 块级元素
`margin: 0 auto `

- 使用flex
```css
 display: flex;
 justify-content: center;
```

- 使用transform 
```css
.son{
    position:absolute;
    left:50%;
    transform:translate(-50%,0);
}
```
-  使用left:0, right:0
```css 
.son{
    position:absolute;
    width:固定;
    left:0;
    right:0;
    margin:0 auto;
}
```
