### ISSUE TITLE
vscode plugins list 

### ISSUE THREAD

**Issue by hapiman** [hapiman/jsrice#2]
- ESLint 会直接使用项目下的`.eslintrc`作为标准进行检查

**Comment by hapiman** [comment]
`eslint`常用的配置
```yaml
# root
root: true

# code env
env:
  node: true
  mocha: true
  es6: true

# rules
rules:
  # basic
  semi: [error, never]
  quotes: [error, single]
  eqeqeq: error
  camelcase: error
  radix: error
  yoda: error
  no-var: error
  no-const-assign: error
  strict: [error, global]
  comma-dangle: [error, only-multiline]

  # indent
  indent: [error, 2, { SwitchCase: 1 }]

  # brace
  curly: [error, multi-line]
  brace-style: error

  # disable default
  no-unused-vars: off
  no-console: off
  no-unreachable: off
  require-yield: off
  no-constant-condition: off

parserOptions:
  ecmaVersion: 6

extends:
  - 'eslint:recommended'
  - .eslintrc-sails

```
